### ISSUE TITLE
Error: Usernames with numbers break the git lookup

### ISSUE THREAD

**Issue by dben** [andjosh/clubhouse-cli#145]
https://github.com/andjosh/clubhouse-cli/blob/f5946ef33315fe207df51853f5a8506ec9657154/src/bin/club-story.ts#L134

If a username has a number, it will break parsing the issue number from a branch name.

The issue Id lookup just gets the first number found in the branch name. This might work a little better:
```
let id = parseInt(branch.match(/\*.*/)[0].match(/\/ch([0-9]+)/)[1], 10);
```

**Comment by andjosh** [comment]
Released in v2.3.0
