### ISSUE TITLE
Support clubhouse branch format

### ISSUE THREAD

**Issue by j-martin** [andjosh/clubhouse-cli#38]
Clubhouse supports automatic status changes if you use their branch format. https://help.clubhouse.io/hc/en-us/articles/207540323-Using-the-Clubhouse-GitHub-Integration-with-Branches-and-Pull-Requests

### Expected Behavior

Create a branch matching: `<mention-name>/ch<id>/<title>`

### Actual Behavior

> Create git branch from story slug `<type>-<id>-<title>`

### Steps to Reproduce

`club story <id> --git-branch`        

The change is trivial to make, but I was wondering if @andjosh was interested in accepting a PR for it. We could also add another flag if the current behavior/format is desired.

**Comment by j-martin** [comment]
We experimented a bit, their integration really cares about the `<mention-name prefix>/ch<id>/<anything-really>`. As you can see in the prescribed format.

<img width="641" alt="screen shot 2018-11-07 at 10 10 10" src="https://user-images.githubusercontent.com/4259753/48151229-9560cc00-e275-11e8-84e1-c3602542f7ce.png">

For example, `ch<id>/<random-text>` did not work.

The `mention name` is crucial to assign the proper user (without using email and what not).
<img width="634" alt="screen shot 2018-11-07 at 10 12 44" src="https://user-images.githubusercontent.com/4259753/48151266-b3c6c780-e275-11e8-918b-54ea7073dbd4.png">

But yeah, the integration is by definition insecure as far as being able to impersonate anybody.

As far as making it user definable, it think it is reasonable, but we mostly just care about using the format prescribed by CH.

**Comment by j-martin** [comment]
Yes, that would do it. We could also have a flag like `--git-standard-branch` for the format without the story type. I am good either way.

**Comment by andjosh** [comment]
Sounds good. I'm fine with replacing the current behavior of `--git-branch` with this CH-integrated branch naming since this _is_ a library for the CH system. :)

We can definitely keep the old behavior in `--git-branch-standard`.

We should be able to get the user's handle with https://github.com/clubhouse/clubhouse-lib/blob/master/src/index.js#L139

**Comment by andjosh** [comment]
Released in v1.9.0
