### ISSUE TITLE
Rename `find` to `search` to be more consistent with Clubhouse

### ISSUE THREAD

**Issue by j-martin** [andjosh/clubhouse-cli#58]
Search Operators, the Search Section in the UI, the `/api/v2/search/story`, etc.

We could use aliases, but I am tempted to use them for shorthands (e.g.: `search` -> `s`) and only one alias can be used per command.

**Comment by andjosh** [comment]
I think this makes sense.

I initially named the `find` method differently in anticipation of clubhouse eventually surfacing their `search` interface and this CLI using that endpoint (it wasn't available initially).

Do you think the `search` command should just hit the actual endpoint and then `find` can be for the flag-based interface?

**Comment by j-martin** [comment]
I was considering adding `git mv club-find club-search` and create `club-find` that points to the `main` fn of `club-find`. This would be done to preserve backward compatiblity, so maybe add a deprecation warning or something.

As mentioned in https://github.com/andjosh/clubhouse-cli/pull/55#issuecomment-466480045 I think we should keep the same code and pair down the potential code duplication and drift. Also, I see the old approach going away sooner than later (or only keep what is not done by the api).

Also, it would pretty be confusing for users: 

> What? `find` and `search` gives me different results (potentially).

**Comment by andjosh** [comment]
Yeah, I agree.
