### ISSUE TITLE
Proposal: Convert to Typescript

### ISSUE THREAD

**Issue by j-martin** [andjosh/clubhouse-cli#66]
@andjosh would you be open to migrating (me) the project to typescript. 

The mistake/bug introduce with my previous refactoring would have been detected automatically. Then editors like VSCode, the Intellij-family or anything supporting LSP get supercharged.

Let me know what you think.

**Comment by andjosh** [comment]
I'd be open to that!
I don't have much experience with TypeScript (I've used Flow), but if you're up for it, I'm on board.
